### ISSUE TITLE
Clang format language is Cpp

### ISSUE THREAD

**Issue by ChillerDragon** [MilkeeyCat/ddnet_protocol#10]
https://github.com/MilkeeyCat/ddnet_protocol/blob/6827ae22523221db04bf463b6d5d79285ed4b630/.clang-format#L2

feature or bug?

**Comment by ChillerDragon** [comment]
Hm I tried C it does not seem to exist. Does clang even properly support C?

**Comment by MilkeeyCat** [comment]
It supports C but `Language` has to be `Cpp` https://gist.github.com/idelsink/c25049d8c987890935f4#file-clang-format-L43

**Comment by MilkeeyCat** [comment]
https://clang.llvm.org/docs/ClangFormatStyleOptions.html#language there's `C` language :D
