### ISSUE TITLE
typedef some bool?

### ISSUE THREAD

**Issue by ChillerDragon** [MilkeeyCat/ddnet_protocol#14]

**Comment by MilkeeyCat** [comment]
If you use booleans, sure

**Comment by ChillerDragon** [comment]
https://github.com/MilkeeyCat/ddnet_protocol/pull/15/commits/088e509fb3091783696dd937cffb994277dd1b8f#diff-2c8dc3df0acfa13231d6e765dee3f380195dfcbe88169d22d7f0439760f23d5eR50

**Comment by MilkeeyCat** [comment]
ye, you can include `stdbool` for bloat and use 
```c
typedef enum { false, true } bool;
```
for non bloat

**Comment by ChillerDragon** [comment]
Completed? We got a bool yet?
