### ISSUE TITLE
plan user facing api for packet and message decoding

### ISSUE THREAD

**Issue by ChillerDragon** [MilkeeyCat/ddnet_protocol#28]
There are 3 types of packets:
- control
- connless
- normal??xd the one with game and system messages

For this I think a union would be really cool!

```C
typedef struct {
        union {
            ControlPacket *control;
            ConnlessPacket *connless;
            NormalPacket *normal;
        } packet;
        PacketHeader *header;
	PacketKind kind;
} Packet;
```

Then the normal packet has as a payload a list of game and system messages.
Here usually an array comes to mind.
But the problem is that it is an array of mixed types.
These polymorphic arrays can be a bit ugly in strictly typed languages.
Some script languages have duck typing as a feature.
In C also everything can be casted into whatever you want, but meh.

One thing I tried in assembly is to use callbacks instead. And I really liked it.

So when you decode a packet you provide it with a function pointer that will be called
for every message that is included in the packet.
Or even better you provide it with a struct of multiple function pointers.
One function pointer for every message.

```C
#include <stdint.h>
#include <stdio.h>

// lib code
typedef struct {
	int client_id;
	const char *message;
} MsgChat;

typedef struct {
	void (*on_chat)(MsgChat *msg);
} MessageCallbacks;

void decode(int32_t *data, MessageCallbacks *callbacks) {
	MsgChat msg;
	msg.message = "hello";
	callbacks->on_chat(&msg);
}

// user code
void on_chat(MsgChat *msg) {
	printf("[chat] %s", msg->message);
}

int main() {
	MessageCallbacks callbacks;
	callbacks.on_chat = on_chat;
	decode(NULL, &callbacks);
}
```

Imo this is really cool for unpacking and the user gets some kind of event system for free.
Also memory management is easy. No dynamically growing arrays that have to be allocated.
If the user wants to keep the data he can do a copy.

Two problems I see with this are:
- potentially annoying for the user to setup the big callback struct (that could be solved with a memset 0 and by ignoring nullptr callbacks from the lib. Plus one generic ``on_message(void *data, MsgType type)`` callback thats called for all messages)
- it does not work well for repacking. If you want to build a proxy that changes packets you cant do ``pack = unpack(data);pack.new_attr = 2;pack.pack()`` because you never get a full packet struct

**Comment by ChillerDragon** [comment]
Yeah I never used unions in my life haha. Im kinda hyped about using them. Also looks cool on the chunk.
```C
void on_chunk(Chunk *chunk) {
  if(kind == MSG_CHAT) {
    chunk->msg_chat.message; // chat message
  }
}
```

Indexing the chunk with the message type seems a bit redundant but it seems fine since the chunk abstracts away multiple types. Also the user or even the library can further abstract on it to only extract the message types so it becomes cleaner. One thing I see as error prone is the user has to access the right field in the union. If the user reads ``chunk.cl_say`` instead of ``chunk.sv_chat`` weird stuff will happen.

Also in your proposal the messages are by value and not pointers. This means that every chunks memory foot print is as big as the biggest net message.

Speaking of memory. Where do we store the chunks? In the ``Packet`` struct? As an array? Fixed size? malloc? Who frees the data? Can the user append to that array and repack the packet?

**Comment by MilkeeyCat** [comment]
> One thing I see as error prone is the user has to access the right field in the union. If the user reads chunk.cl_say instead of chunk.sv_chat weird stuff will happen.

I would expect from people who write C code to be able to check `kind` field before reading the chunk value xd,

> Speaking of memory. Where do we store the chunks? In the Packet struct? As an array? Fixed size? malloc? Who frees the data? Can the user append to that array and repack the packet?

There're possible to ways how  to do it, first one allocate chunks on heap and store them as: 
```C
typedef struct {
    Chunk *chunk;
    size_t len;
} NormalPacket;
```
This way users would have to free allocated memory themselves, and if you want to append an element you would have to allocate a new block of memory, copy existing chunks and then append your own. 
The second one is to use fixed array:
```C
typedef struct {
    Chunk chunk[MAX_CHUNKS];
    size_t len;
} NormalPacket;
```

I'm fine with both but I personally like second one more.

**Comment by ChillerDragon** [comment]
Having max chunks sounds sane. It can even be calculated. Its max packet payload divided by shortest chunk size. Without checking any code I freestyled ``1500/3`` in my head which is ``500`` so a ``MAX_CHUNKS = 512`` should be too much in 99% of the cases but enough in 100% of the cases.

**Comment by MilkeeyCat** [comment]
"It's better to have too much than not enough" - MilkeeyCat, probably.

**Comment by ChillerDragon** [comment]
Hmmm there are some big net messages such as [tune params](https://chillerdragon.github.io/teeworlds-protocol/06/game_messages.html#NETMSGTYPE_SV_TUNEPARAMS) which holds 33 integers. And if the `Chunk` struct is a union of all messages it is at least 33 integers big. That means that ``Chunk chunk[MAX_CHUNKS];`` is **67584 bytes big** that seems a bit high. Calculated using `33*512*4` (33 is the chunk size in integers, 512 is the array length and 4 to turn the 32 bit integers into bytes).

**Comment by MilkeeyCat** [comment]
Then it's time to use big brain strat and store a pointer to the chunk, not the chunk itself.

**Comment by MilkeeyCat** [comment]
I mean this:
```C
typedef struct {
	ChunkKind kind;
	ChunkHeader header;
	union {
		MsgRconCmd *msg_rcon;
	} msg;
} Chunk;
```

**Comment by MilkeeyCat** [comment]
Also, I don't know if there should be a name for the union, maybe just `union {...};` would be better, so you could get data as `chunk.msg_rcon` and not `chunk.msg.msg_rcon`. Or would this be more confusing? :\

**Comment by ChillerDragon** [comment]
If the message is a pointer who allocates the memory?

**Comment by MilkeeyCat** [comment]
The library will allocate the memory, and it will be the user's task to free it. Maybe we could add a function `free_packet` which would free all of the dynamically allocated memory.

**Comment by ChillerDragon** [comment]
Okay so now #52 is merged and it uses the array by value. So the next step is to refactor it?
I am not sure about the malloc. I always stay away from malloc because I think it is hard and slow.

Calling malloc multiple times for every incoming packet seems a bit bloated. Imo ideally there would be 0 mallocs per incoming packet. Not even for the packet struct it self. The user can allocate a buffer once and pass that to the decode function. The packet header is 3 bytes the maximum payload is 1400 bytes even with huffman compression there should not be such a big value for the total amount of bytes needed even for the parsed and decompressed version.

Maybe returning one big struct that contains everything can not be done smooth and efficient. I still like the idea of passing an on message callback to the decode packet function. Or we could also let chunks not contain parsed messages just the header with the size and a pointer to the payload. And then let the user iterate the chunks and call the parse message function.

Maybe we should first draft out a full ideal usage of the user facing side. And then see if it can be achieved internally. Looking at only decoding packets how much work and code should a user of the library have to do? Is it one method call to receive a full struct with everything? Or is it multiple?

A question is also if the huffman decompression is responsibility of the user or if it should happen magically.
Here is one verbose example I drafted where the user has lots of control and where the decode method does not decompress or parse messages. This one seems easy to implement on the library side. The question is. Is it convenient enough on the user side.

```C
uint8_t *data;
uint8_t payload[MAX_PACKET_SIZE];
size_t len = udp_read(data);

PacketHeader header = decode_packet_header(data);
if(header.flags & PACKET_FLAG_COMPRESSION)
	huffman_decompress(data + PACKET_HEADER_SIZE, len - PACKET_HEADER_SIZE, payload, sizeof(payload));
else
	memcpy(payload, data, len);

Error err;
Packet packet = decode(payload, len, &err);

if(packet.kind == PACKET_NORMAL) {
	for(int i = 0; i < packet.header.num_chunks) {
		Chunk *chunk = packet.chunks[i];
		Message *msg = decode_message(chunk->payload, chunk->header.size);
		if(msg.kind == MSG_RCON_CMD) {
			puts(msg.rcon.cmd);
		}
	}
}
```

**Comment by MilkeeyCat** [comment]
Ok, I think we can provide two ways for working with packets/messages. One will returns all packets and it will call malloc, and the other one where the user will be able to pass a callback function

**Comment by ChillerDragon** [comment]
So you prefer callback over the version I drafted where the user calls decode message manually?

**Comment by MilkeeyCat** [comment]
I'll make a branch with my idea later

**Comment by ChillerDragon** [comment]
I would say most of the discussion here is either implemented or outdated.
Closing as completed. A new refactor can get a new clean issue.
