### ISSUE TITLE
oop variable naming

### ISSUE THREAD

**Issue by ChillerDragon** [MilkeeyCat/ddnet_protocol#35]
The current code looks like this I am not sure if i like it

```C
int32_t unpacker_get_int(Unpacker *state);
```

Talking specifically about the ``*state``. I would prefer either ``*unpacker`` or ``*self``.
That style will be used else where I guess.

```
{struct_name}_{oop_styled_instace_method_name}({struct_instance}, [args..])
```

Like

```C
void packet_unpack(Packet *self, uint_t *data);
uint_t *packet_pack(Packet *self);
```

**Comment by MilkeeyCat** [comment]
Seeing `self` parameter in C code feels weird to me(that's a me problem), imo `uint_t *packet_pack(Packet *packet);` is better but both are fine to me.

**Comment by ChillerDragon** [comment]
Okay then let's go with struct name!

**Comment by ChillerDragon** [comment]
The feature of self is that it is short to type. Typing out unpacker can be a bit long but it should be fine.
