### ISSUE TITLE
bindings for other languages

### ISSUE THREAD

**Issue by ChillerDragon** [MilkeeyCat/ddnet_protocol#36]
i know there isn't really any code yet xd and this might sound a bit premature

But what do you think about bindings for python, ruby and lua or whatever we feel like. It being written in C makes it pretty portable. I mean it can even be integrated into the linux kernel hehe. So portability could become one of the core goals of this library. All the big C libraries have bindings in other languages. Often these are maintained by someone else in another repository.

@MilkeeyCat who do you think about sprinkling in a bit of high level scripting code to make the bindings work and add the bindings directly into this repo? Or will it bloat stuff up too much?

The usage of C is already barely holding the 50% if we add a few bindings the boilerplate code in other languages will probably pollute the stats to a degree that it is non obvious that this even is a C library. But I am not sure if that is something you care about.

![image](https://github.com/user-attachments/assets/04c5280a-078a-40c5-ae63-f6a8f9d46e00)

**Comment by MilkeeyCat** [comment]
I don't care about library's language usage stats. I'd say it would be ok add binding either when someone will ask for them(won't happen, because we are the only 2 people who's gonna use this library xd) or when the library will be almost ready. Also, doesn't libtw2 provide some bindings?

**Comment by ChillerDragon** [comment]
libtw2 has python bindings for huffman. I don't really know libtw2s net code but I think it has no bindings. I still think there is value in a python package that provides huffman by depending on a C instead of rust compiler.

**Comment by ChillerDragon** [comment]
Okay then I will resist the urge to add any bindings before the library is actually finished xd

**Comment by ChillerDragon** [comment]
Okay so no bindings before completion of the library. Seems reasonable. No need to keep the open issue around for eternity.
