### ISSUE TITLE
return values for success and error?

### ISSUE THREAD

**Issue by ChillerDragon** [MilkeeyCat/ddnet_protocol#38]
https://github.com/ddnet/ddnet/issues/6436

I am leaning towards ddnet style. So ``true`` for success.

If statements look nice if it is ``true`` for success.

```C
if(this_works()) {
  puts("uwu");
}
```

Some C libs like to use 0 for success and error code otherwise. But I think that does not fit the library style so far. We set some ``err`` variable instead. If we really need that we can still return the ``Error`` enum instead of a ``bool``.

```C
if(this_works() == ERR_NONE) {
  puts("uwu");
}
```

**Comment by MilkeeyCat** [comment]
My idea from start was to return `Error` if function can fail and pass `Error*` in a function if it can error but also has to return some value:
```
Error this_works() {
    ...
}

Chunk this_works(Error *err) {
    ...
}
```

**Comment by ChillerDragon** [comment]
Okay. So do not use booleans use `Error` instead.
