### ISSUE TITLE
what is the plan for ``decode()``

### ISSUE THREAD

**Issue by ChillerDragon** [MilkeeyCat/ddnet_protocol#43]
Is decode supposed to be the main method a user calls to decode a full packet?

https://github.com/MilkeeyCat/ddnet_protocol/blob/a77a6c59207e45b879ca668db6097a3dbec0dea4/src/packet.c#L12

What does it return? Its signature says ``PacketKind`` but it also returns ``PacketControl`` is that supposed to stay like that?
Or do you have a plan here @MilkeeyCat ?

**Comment by MilkeeyCat** [comment]
At first I had an idea to return `PacketKind *` and then user would have to cast the pointer to correct packet kind, but `union` can probably be used and no need for this black magic.

**Comment by ChillerDragon** [comment]
We have a union now :rocket:
