### ISSUE TITLE
move `token` into `PacketHeader`

### ISSUE THREAD

**Issue by ChillerDragon** [MilkeeyCat/ddnet_protocol#49]
https://github.com/MilkeeyCat/ddnet_protocol/blob/a77a6c59207e45b879ca668db6097a3dbec0dea4/include/ddnet_protocol/control_packet.h#L14-L19

The cursed ddnet protocol TKEN extension puts its security tokens at the end of the payload. But conceptually they belong into header. So the normal and control packets will both have a security token. Imo it would be nicer to move the `token` field out of the `PacketControl` into the `PacketHeader`. Thoughts @MilkeeyCat ?

**Comment by MilkeeyCat** [comment]
I agree, it would be nice to move it.
