### ISSUE TITLE
Should header files contain `extern "C"`?

### ISSUE THREAD

**Issue by MilkeeyCat** [MilkeeyCat/ddnet_protocol#61]
If we include 
```C
#ifdef __cplusplus
extern "C" {
#endif

// declarations here

#ifdef __cplusplus
}
#endif
```
in header files this would allow C++ library users include headers files simply as `#include<ddnet_protocol/chunk.h>`

**Comment by ChillerDragon** [comment]
Yes that would be nice! The users code should always be as clean and short as possible.

So that brings C++ compatibility into scope? No C only features?

**Comment by MilkeeyCat** [comment]
I think `uint8_t buf[static len]` is not a big game changer to use it and not have compatibility with C++

**Comment by MilkeeyCat** [comment]
> So that brings C++ compatibility into scope
We have tests written in C++ xd

**Comment by ChillerDragon** [comment]
Yea fair. Okay then we stay in the subset of C and C++
