### ISSUE TITLE
What is the plan for documentation?

### ISSUE THREAD

**Issue by ChillerDragon** [MilkeeyCat/ddnet_protocol#9]
Examples? Or only signatures? Where?

Everything in the README.md? docs/ with markdown? Only in comments? Generated with doxygen or similar? External website?

**Comment by MilkeeyCat** [comment]
I guess there should be a markdown file with a list of signatures and maybe a file with examples

**Comment by ChillerDragon** [comment]
@MilkeeyCat in the readme directly? Or where?

**Comment by MilkeeyCat** [comment]
Ye, I guess readme is fine, there isn't much to write in there anyways

**Comment by MilkeeyCat** [comment]
At the same time I think it would be nice to have function descriptions above signatures in header files, so you don't have to open readme each time you want to check what the function does :\

**Comment by ChillerDragon** [comment]
> At the same time I think it would be nice to have function descriptions above signatures in header files, so you don't have to open readme each time you want to check what the function does :\

Yes neovim BTW. Which style of comments? Document return type and params with @return and @param ddnet styled?

**Comment by MilkeeyCat** [comment]
Mostly just what it does, param and return thingy can be used if a function does some black magic you wouldn't know without looking at the code.(nice ping for return and param xd)

**Comment by ChillerDragon** [comment]
Then I would recommend generating mark down based on C code comments. And write the docs when creating a new function.

**Comment by MilkeeyCat** [comment]
Ye, that would be better, because otherwise it would be just copying same docs from code to readme, and keeping them up to date not fun
